### ISSUE TITLE
RedTalaria for UE 5.1 setup says it requires Hermes which is a UE 4 plugin

### ISSUE THREAD

**Issue by davidtveraas** [cdpred/RedTalaria#1]
The setup instruction say to setup Hermes, but the link is for a UE 4 Plugin. 

When I attempt to setup the Hermes Plugin in UE 5.1, I get the message: 

Missing Modules
The following modules are missing or built with a different engine version: 
HermesServer
HermesContentEndpoint
Engine modules cannot be compiled at runtime. Please build through your IDE.

Such an error would be expected when the Plugin is for the incorrect version. 

Is there another version of Hermes which was used in the UE 5.1 test for RedTalaria? Please advise.

**Comment by zosiu** [comment]
Hey, 
Hermes should work with UE 5.1, the message is just telling you to build the project first:
> Engine modules cannot be compiled at runtime. Please build through your IDE.

so that these Hermes modules get compiled and after that you should be able to use them. 
Same thing has to be done with RedTalaria.

**Comment by davidtveraas** [comment]
Thank you for the reply. How can I build a project without running/opening the project? I am confused on what this means.

**Comment by zosiu** [comment]
Maybe try following this tutorial: https://www.youtube.com/watch?v=2HHJ6AYnwFw (since it seems like you are not building through an IDE).

**Comment by davidtveraas** [comment]
I appreciate the help. I tried it on another project with a new Plugins folder and it gave me the option to build. Perhaps there is something conflicting with the first project I tried? I am simply trying it out, so this will suffice. Thanks again!
